### ISSUE TITLE
error: system/sepolicy/Android.bp:95:15: can't assign select statement to non-configurable property "required"

### ISSUE THREAD

**Issue by lunik1980-code** [EverestOS-AOSP/system_sepolicy#1]
error: system/sepolicy/Android.bp:95:15: can't assign select statement to non-configurable property "required". This requires a small soong change to enable in most cases, please
 file a go/soong-bug if you'd like to use a select statement here
fatal errors encountered

**Comment by mvimal2607** [comment]
> error: system/sepolicy/Android.bp:95:15: can't assign select statement to non-configurable property "required". This requires a small soong change to enable in most cases, please file a go/soong-bug if you'd like to use a select statement here fatal errors encountered

This is WIP org
Our stable source is here ---> https://github.com/projecteverest
